### ISSUE TITLE
Bugs after upgrading to Anki v2.1.26

### ISSUE THREAD

**Issue by RonilPatel7** [glutanimate/html-cleaner#5]
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-18 22:03:32

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 34, in cmd
  File "aqt\webview.py", line 114, in _onCmd
  File "aqt\webview.py", line 518, in _onBridgeCmd
  File "aqt\editor.py", line 408, in onBridgeCmd
  File "C:\Users\Ronil Patel\AppData\Roaming\Anki2\addons21\html-cleaner\html_cleaner\editor.py", line 30, in onHtmlClean
    shift_and_click = modifiers == Qt.ShiftModifier
NameError: name 'Qt' is not defined

I noticed the bug when attempting to use the add on by using the shortcut (Alt+M):

Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-18 22:03:32

Caught exception:
Traceback (most recent call last):
  File "aqt\editor.py", line 228, in <lambda>
  File "C:\Users\Ronil Patel\AppData\Roaming\Anki2\addons21\html-cleaner\html_cleaner\editor.py", line 30, in onHtmlClean
    shift_and_click = modifiers == Qt.ShiftModifier
NameError: name 'Qt' is not defined

**Comment by RonilPatel7** [comment]
resolved with using: https://github.com/ijgnd/html-cleaner
